
services:
  streamlit:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "9602:9602"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:9602"]
      interval: 30s
      timeout: 10s
      retries: 3

  ngrok:
    image: wernight/ngrok
    command: ngrok http streamlit:9602 --log=stdout
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    ports:
      - "4040:4040"
    depends_on:
      - streamlit
    env_file:
      - .env
    restart: unless-stopped

  tests:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["pytest", "--disable-warnings"]
    depends_on:
      - streamlit
      - ngrok
    volumes:
      - .:/app
    working_dir: /app