services:
  streamlit:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8501:8501"
    restart: always

  ngrok:
    build:
      context: .
      dockerfile: Dockerfile.ngrok
    environment:
      NGROK_AUTHTOKEN: 2kLCErWxj0kzjTO7ipm3FMoNgrn_R9zhNZBSKCeLWnNjExQV
    ports:
      - "4040:4040"  # Expose ngrok web interface
    command: 
      ngrok http streamlit:8501 --log=stdout &
      sleep 15 &&
      curl --silent http://127.0.0.1:4040/api/tunnels | jq -r '.tunnels[0].public_url'
    depends_on:
      - streamlit  # Ensure ngrok starts only after Streamlit is up
    restart: always
    #command: ngrok http streamlit:8501 --log=stdout
    #ports:
    #  - "4040:4040"  # Expose ngrok's web interface for inspection
    #restart: unless-stopped
