version: '3.8'

services:
  streamlit:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8501:8501"
    restart: always

  ngrok:
    build:
      context: .
      dockerfile: Dockerfile.ngrok
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    ports:
      - "4040:4040"
    depends_on:
      - streamlit
    restart: unless-stopped